[shortcut]
# Shortcut to save crop image shown on screen
save_crop_image = "KeyP"
# Shortcut modifier for local zoom (hold + click to zoom individual image)
local_zoom_modifier = "KeyW"
# Shortcut modifier for local rotation (hold + click to rotate individual image)
local_rotate_modifier = "KeyE"
# Shortcut to toggle the multicursor
switch_cursor = "KeyC"
# Shortcut to switch between layout (grid, stack; horizontal ...)
switch_layout = "KeyL"
# Shortcut to rotate all images
rotate_images = "KeyR"
# Shortcut to toggle add mode (dropped images are added instead of replacing)
add_images = "KeyQ"

[text]
# Color of the image name shown in the corner
font_color = { "Srgba"= { "red"= 0.0, "green"= 1.0, "blue"= 0.0, "alpha"= 1.0}}
# Font size of the image name
font_size = 16.0

[hdr]
enabled = false

[misc]
# Enable the zoom on mouse scroll
scroll_behavior = "None"
# Width of the grid (0: auto)
grid_width = 0
# Texture interpolation mode (Nearest or Bilinear)
sampler_mode = "Nearest"